### ISSUE TITLE
[Feature Request] Shizuku compatibility

### ISSUE THREAD

**Issue by VictorVow** [Domi04151309/Android-Power-App#14]
**Describe the solution you'd like**

[Shizuku](https://github.com/RikkaApps/Shizuku/) is an alternative to rooting which allows apps to run commands that normally require ADB, and can be installed without rooting. 

It'd love for this app to be compatible because I'm reducing the security hole by removing root on my phone but I'd still like access to a few useful utilities like this one.

**Comment by Domi04151309** [comment]
This is not planned for now.
