### ISSUE TITLE
[Feature  Request] sheduling power off at a specified time

### ISSUE THREAD

**Issue by nicoursi** [Domi04151309/Android-Power-App#3]
It would be nice if you could schedule a graceful power off of the device.

E.g. the user can set it to power off every day at 1 am.

**Comment by v1nc** [comment]
Also consider adding something like a sleep timer, e.g. turn off in x mins.

This is an relatively easy to implement feature that is still missing in the most distributions.

**Comment by nicoursi** [comment]
I had a look at the code and I notice it doesn't turn off gracefully.

To turn off gracefully you should use this:
`am start -a com.android.internal.intent.action.REQUEST_SHUTDOWN`

See reference for more details https://android.stackexchange.com/questions/47989/how-can-i-shutdown-my-android-phone-using-an-adb-command

**Comment by Domi04151309** [comment]
> It would be nice if you could schedule a graceful power off of the device.
> 
> E.g. the user can set it to power off every day at 1 am.

This sounds like a nice idea but it's rather something for a new app because this app is just a very simple tool for power options.

**Comment by nihal697** [comment]
What about the graceful reboot thing? Isnt it nicer?
