### ISSUE TITLE
[Feature Request] Reboot to EDL

### ISSUE THREAD

**Issue by JonnyTech** [Domi04151309/Android-Power-App#6]
Can you add reboot to EDL, same as Magisk Manager, please?

![magisk](https://user-images.githubusercontent.com/3584732/82962257-9ff9c800-9fb7-11ea-8b4e-e50765302ef5.png)

**Comment by Domi04151309** [comment]
Okay, I tried implementing this and it hard bricked my phone. Can you help me, please?

**Comment by Domi04151309** [comment]
Okay, I got my phone to boot up again but I don't know if I implemented it correctly. Is the adb shell command "reboot edl" the right one?
