### ISSUE TITLE
[Bug Report] Won't Allow Me To Install To My Rooted Phone (xt1563)

### ISSUE THREAD

**Issue by n6bhu** [Domi04151309/Android-Power-App#9]
I tried to install this app (from Fdroid) to my phone (Moto X Play xt1563 running Android 7.1 rooted with twrp-lux-3.2.3-r1.img) and it returned error: [sic.] "The privaledged permissions have not been granted to the extension! Please create a bug report!"

<details>
  <summary><b>Screenshots</b></summary>

  _Add screenshots here to describe the problem._
</details>

<details>
  <summary><b>Logs</b></summary>

  _Add a detailed stack trace / crash log here if applicable_
</details>

**Additional information**

 - Android version: _System Settings > About > Android version (varies per device)_
 - Power App version: _Settings > About > Version_
 - Installation source: _Google Play / F-Drod / Own Build_

**Comment by Domi04151309** [comment]
This is not related to this application. Contact F-Droid.
